name: mfm_parser
description: mfm (Markup Language For Misskey) parser for dart. it provides feature that text convert
              misskey node and properties.
version: 1.0.1
homepage: https://github.com/shiosyakeyakini-info/dart_mfm_parser

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.16.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: